### ISSUE TITLE
Publish this!

### ISSUE THREAD

**Issue by lukecyca** [jakob/TableTool#1]
Hey Jakob,

This is a nice little tool, and there is really no other simple CSV viewer available for Mac. So unfortunately everybody just uses Excel as the _de facto_ csv viewer.

I was able to download this source and build it. You should post a build on https://eggerapps.at for those that don't have XCode at the ready.

Cheers,
Luke

**Comment by jakob** [comment]
Hi Luke!

I made this tool last summer together with @aigi, who worked as an intern in my company (he did all the actual programming). Unfortunately I never found the time to polish it enough for release. I don't want to put it on my website in its current state, because I'm a bit scared of having to support it.

However, I agree that it might be useful to people, so I uploaded a build to the releases section:
https://github.com/jakob/TableTool/releases

Now people can use it without installing XCode :)

**Comment by lukecyca** [comment]
Sounds good!

**Comment by jakob** [comment]
Hey Luke!

I just wanted to let you know that we've been working on Table Tool. @SandroPeham polished the UI, made an icon, and did all the other things that are necessary for releasing it.

We now released Table Tool version 1.1.

You can download it right here on Github or on the Mac App Store!
