### ISSUE TITLE
Allow for pipe delimited files

### ISSUE THREAD

**Issue by scwood** [jakob/TableTool#8]
This would be useful for me. I wouldn't mind diving in and contributing if that's an option.

**Comment by jakob** [comment]
I'd love to see contributions to Table Tool!

My main concern for Table Tool is that I want to keep the UI as simple as possible -- that's why it is limited to the 3 most popular delimiters (comma, semicolon and tabs).

So the questions I'm asking myself are:
- Are pipes commonly used for CSV-like files?
- Are there any other delimiters that are commonly used? 
- Would it make more sense to add pipes as a 4th option, or should we allow arbitrary delimiters?

**Comment by alainravet** [comment]
I've just ran into this problem (a pipe-delimited csv file), so I'd say "Yes" for this request.
Allowing any arbitrary delimiter (single-character ?) seems a future-proof solution.

**Comment by jakob** [comment]
OK, pipe-delimited files seem like a good idea. I'd like to hear some more specifics, though.

What kind of software uses pipe-delimited files?

Is it the default format, or is it a custom format? If it is a custom format, why was it chosen instead of standard CSV?

Right now I don't see a strong case for allowing arbitrary characters as separators. Sure, it would be "future-proof", but it would make the UI more complicated. I want Table Tool to be intuitive and easy to use above all else; it does not need to support every corner case, especially if doing so would make the app harder to understand.

**Comment by alainravet** [comment]
@jakob 

> What kind of software uses pipe-delimited files?

In my case, we send Neolane (now part of Adobe) our analytics data separated with pipe. It may be legacy, but that's how it is.

CSV (_comma-separated_) and TSV (_tab-separated_) are particular cases of [DSV (_delimiter-separted_)](https://en.wikipedia.org/wiki/Delimiter-separated_values)

> Any character may be used to separate the values, but the most common delimiters are the **comma**, **tab**, and **colon**.[1]:113[4] The vertical bar (also referred to as **pipe**) and **space** are also sometimes used.[1]:113 In a comma-separated values (CSV) file the data items are separated using commas as a delimiter, while in a tab-separated values (TSV) file, the data items are separated using tabs as a delimiter.

**Comment by bshields-idatainc** [comment]
Pipe-delimited files are common when dealing with processing systems with poorly-written CSV parsers that can't handle data with included commas, so they pick a visible character like the "pipe" which is virtually never in data.

I'm not particular whether the ability to handle pipes is done via an additional separator choice or via a "pick any character" dialog, but I would vote to have pipes included somehow.

**Comment by jakob** [comment]
The [latest version of Table Tool](https://github.com/jakob/TableTool/releases) now supports using pipes as delimiters.

You have to manually select it though; the heuristic does not auto-detect pipes yet, unfortunately.
